select 
f.CollectionName as SOURCE, 
n.CId as CID	,
n.LAC	,
n.MCC,
n.MNC	,
n.Operator	 ,
n.CGI	,
n.technology	Technology,
p.longitude  Lon,
p.latitude	Lat,
l.SessionId,
l.TestId,
l.NetworkId,
f.Zone SystemName,
f.ASideDevice ADevice,
l.MsgTime Time,
l.PosId,
n.FileId, 
'' as BTSLon,
'' as BTSLat,
p.longitude  BTSLonDiff	, 
p.latitude	  BTSLatDiff,
'' BTSDist	,
p.longitude  BTS2LonDiff	, 
p.latitude	  BTS2LatDiff,
	''	BTS2Dist ,
p.longitude  BTS3LonDiff	, 
p.latitude	  BTS3LatDiff,			
'' BTS3Dist	,
'' BTSTech	,
'' FloorPlanName,
'' FloorPlanLevel ,
'' SessionIdLP	,
'' TestIdLP ,
'' PosIdLP	,
'' NetworkIdLP, 
Str(Round(l.RSRP,1),10,1)as RSRP, 
l.NumMeasuredCells,
Convert(varchar,l.EARFCN) + ' ' + Convert(varchar,l.PhyCellId) as ChPSC


from LTEMeasurementReport l 
 join  NetworkInfo n on  l.NetworkId=n.NetworkId  and l.MsgTime =n.MsgTime   
join  "Position" p on l.MsgTime =p.MsgTime and l.SessionId =p.SessionId and l.PosId =p.PosId
join  FileList f on n.FileId =f.FileId ;
